#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=space_changed action='yabai -m window --focus $(yabai -m query --windows --space | jq -r "map(select(.[\"is-visible\"])) | .[0].id")'

#!/usr/bin/env sh

# bar settings
yabai -m config top_padding 0

yabai -m config active_window_border_color 0xff0000ff # Blue color in hex (0xff is the alpha channel)
yabai -m config normal_window_border_color 0xff000000 # Black color for normal windows
yabai -m config focused_border_width 30               # Set the border width for focused windows
yabai -m config window_border on                      # Enable window borders

# global settings
yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse autofocus

yabai -m config window_placement second_child
# yabai -m config window_topmost               off

yabai -m config window_opacity off
yabai -m config window_opacity_duration 0.0
yabai -m config window_shadow on

yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.90
yabai -m config split_ratio 0.50
yabai -m config auto_balance off

# Mouse support
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

# general space settings
yabai -m config layout bsp
yabai -m config bottom_padding 0
yabai -m config left_padding 0
yabai -m config right_padding 0
yabai -m config window_gap 5

# App specific settings
## float system preferences
yabai -m rule --add app='^System Information$' manage=off
yabai -m rule --add app='^System Preferences$' manage=off

yabai -m rule --add title='Preferences$' manage=off

## float settings windows
yabai -m rule --add title='Settings$' manage=off

## Float authly
yabai -m rule --add app='^Authy Desktop$' manage=off
yabai -m rule --add app='choose' manage=off

echo "yabai configuration loaded.."
