# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme
shell = "zsh"
[plugins]

[plugins.autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"

[plugins.colored-man-pages]
github = "ohmyzsh/ohmyzsh"
use = ["plugins/colored-man-pages/*.zsh"]

[plugins.fzf-zsh-plugin]
github = "unixorn/fzf-zsh-plugin"

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"


# For example:
#
# [plugins.base16]
# github = "chriskempson/base16-shell"
