unameOut="$(uname -s)"
alias x="startx"
alias sttysmall="stty cols 132 rows 45"
alias vim="nvim"
alias tx="tmuxinator"
alias cc="xclip -selection clipboard"
alias killnode="pkill -f node"
alias tmux="TERM=screen-256color-bce tmux"
alias ls="eza -l --git -F --icons --group-directories-first" 
alias ps="procs"
alias hh="$HOME/.config/scripts/cheat.sheat.sh"
alias clip="base64 | xargs -0 printf '\e]52;c;%s\007'"
alias sss="ssh -x remote_server_tmux"
alias cs="google-chrome-stable --profile-directory=Default --app-id=lmgleiefhogfcpmhlkeipbnaddhjeajj"
alias btry="cat /sys/class/power_supply/BAT0/capacity"
alias cat="bat"
alias jp="joplin"
