[tools]
python = "3.12.10"
go = "latest"
rust = "latest"
node = "24.13.0"
pnpm = "latest"
bun = "latest"

starship = "latest"
fzf = "latest"
fd = "latest"
jq = "latest"
ripgrep = "latest"
direnv = "latest"
bat = "latest"
eza = "latest"
delta = "latest"
tmux = "latest"
yazi = "latest"
lazygit = "latest"
lazydocker = "latest"
helm = "latest"


[settings]
experimental = true
python_compile = false
